  - name : copy module
    copy :
      src :  mongo.repo
      dest : /etc/yum.repos.d/mongo.repo

  - name : install mongodb 
    package :
      name : mongodb-org
      state : present

  - name : replacing word
    replace :
      path : /etc/mongod.conf
      regexp : '127.0.0.1'
      replace : '0.0.0.0' 

  - name : enable mongodb
    service :
      name : mongod
      state : started
      enabled : yes
      
