- name : loading app-setup
  import_role :
    name : common
    tasks_from : app-setup

- name : loading java.yaml
  import_role :
    name : common
    tasks_from : java.yaml

- name : loading systemd-setup
  import_role :
    name : common
    tasks_from : systemd-setup.yaml

- name : loading data
  community.mysql.mysql_db :
    name : all
    state : import
    login_user : "{{mysql_login_user}}"
    login_password : "{{mysql_passwd}}"
    login_host : "{{ MYSQL_HOST }}"
    target : "{{ item }}"
  loop :
  - /app/db/schema.sql
  - /app/db/app-user.sql 
  -  /app/db/master-data.sql

- name : restarting
  service :
    name : shipping
    state : restarted



