[local]
localhost

[mongodb]
localhost

[cataloague]
localhost

[reddis]
localhost

[rabbitmq]
localhost

[mysql]
localhost

[user]
localhost

[cart]
localhost

[shipping]
localhost

[payment]
localhost

[frontend]
localhost