- name : loading system user
  import_role :
    name : common
    tasks_from : app-setup

- name : loading nodejs
  import_role :
    name : common
    tasks_from : nodejs

- name : loading systemd-setup
  import_role :
    name : common
    tasks_from : systemd-setup

- name : starting service
  service :
    name : cart
    state : started
    enabled : yes  